### ISSUE TITLE
Improved REST API with correct methods

### ISSUE THREAD

**Issue by Cerfoglg** [benchflow/monitors#24]
Currently we assume that all calls are done with GET on the API. To have a proper RESTful API we need to accept the correct methods, which should be:
- GET for /data
- POST for /start
- DELETE for /stop

If the wrong method is used the monitor should return a HTTP 405 METHOD NOT ALLOWED

**Comment by VincenzoFerme** [comment]
Fixed in https://github.com/benchflow/monitors/pull/25

**Comment by VincenzoFerme** [comment]
Fixed in https://github.com/benchflow/monitors/pull/25
